name: Pistis

on:
  repository_dispatch:
    types: [pistis_manual]

env:
  IVY_API_KEY: ${{secrets.IVY_API_KEY}}
  IVY_API_URL: ${{secrets.IVY_API_URL}}
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Pistis
        run: npm start --markets=${{github.event.client_payload.markets}} --numberOfBanks=${{github.event.client_payload.numberOfBanks}} --merchantIban=${{github.event.client_payload.merchantIban}} --merchantName=${{github.event.client_payload.merchantName}}
